import Head from 'next/head'
import { useRef, useState } from 'react'
import { server } from "../config"

export default function Home() {

  const [link, setLink] = useState(null)
  const inputRef = useRef()

  let redirectURL = server.concat(`/${link}`)

  const handleShortUrl = async (e) => {

    e.preventDefault()

    if (!inputRef.current.value) return 

    let url = inputRef.current.value

    const res = await fetch('/api/shorturl', {
      method: 'POST',
      body: JSON.stringify({ url }),
      headers: {
        "Content-type": "application/json"
      }
    })

    const data = await res.json()
    setLink(data.shortURL)
  }

  return (
    <div>
      <Head>
        <title>ShortUrl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form>
          <div>
            <label htmlFor="">Pega tu URL aquí</label>
            <input autoFocus={true} ref={inputRef} type="text" placeholder="Pega una URL" />
          </div>
          <div>
            <button type="submit" onClick={handleShortUrl}>
              Acortar Url
            </button>
          </div>
          {
            link && <a href={redirectURL}>
              {redirectURL}
            </a>
          }
        </form>
      </main>
    </div>
  )
}
